### ISSUE TITLE
UUID not being pulled when logging in.

### ISSUE THREAD

**Issue by Chevokski** [f1r3fr0st/ajart-studio-edit#1]
When logging into AJ with capture on, I am not getting my UUID pulled up. It is completely blank. I have turned firewall off, restarted the program and my computer. Nothing shows up no matter how many login attempts.

**Comment by GloomyButt** [comment]
I also tried different browsers and uninstalled and reinstalled the required driver.

**Comment by GloomyButt** [comment]
I managed to follow your research and took to Wireshark for my UUID, so the issue is addressed, but you should still see why the program cannot pull the UUID itself.

**Comment by GloomyButt** [comment]
Eh. It's not even worth it, since it turns out this isn't allowed on AJ. I don't want to get banned. I decided to learn the hard way with the MP art program and I think it's more rewarding that way.

**Comment by f1r3fr0st** [comment]
> Eh. It's not even worth it, since it turns out this isn't allowed on AJ. I don't want to get banned. I decided to learn the hard way with the MP art program and I think it's more rewarding that way.

Hello! I apologize for my terribly long hiatus.

This issue has been resolved, WinPcap drivers are no longer compatible with Windows 10 so the program has been updated to use Npcap.

Users are now also required to select their network adapter for capturing network traffic, but everything is good to go.
