### ISSUE TITLE
application won't open

### ISSUE THREAD

**Issue by kohaibun** [f1r3fr0st/ajart-studio-edit#4]
i don't understand how to start the entire application. all i have really available is the art studio edit.snl file and it opens into art studio edit program. nothing happens. i am kinda dumb and slow and have been trying to figure this out for 3 hours. i see it runs off npcap, and i have the latest one installed. but still not working. any kind of advice helps <3

**Comment by v31l-sys** [comment]
Hello! I apologize for not getting to you sooner.. I kind of abandoned my account until recently.

What you are opening is the code files for the program, which require Visual Studio Community 2017 or 2019 to compile

But what you want to download is a release of the program which has already been compiled: https://github.com/v31l-sys/ajart-studio-edit/releases
